api_platform:
    title: 'ECommerce'
    description: "Site E-Commerce des produits des meubles"
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
