<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBDaCqcd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBDaCqcd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBDaCqcd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBDaCqcd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBDaCqcd\App_KernelDevDebugContainer([
    'container.build_hash' => 'BDaCqcd',
    'container.build_id' => '8bf519fc',
    'container.build_time' => 1643903348,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBDaCqcd');
